#!/usr/bin/env python2

import re
import sys
from apiclient.discovery import build

API_KEY="CHANGE_ME"

re_id   = re.compile("v=(\w+)")

if __name__ == "__main__":
    if ( sys.argv.__len__() < 2 ):
        print("Please provide a YouTube URL")
        exit(1)

    url     = sys.argv[1]
    youtube = build("youtube", "v3", developerKey = API_KEY)
    video_id = re_id.search(url).group(1)

    videos_list = youtube.videos().list(
            id         = video_id,
            part       = "snippet",
            maxResults = 1
    ).execute()

    if not videos_list["items"]:
        print("Video '%s' was not found.", video_id)

    video = videos_list["items"][0]["snippet"]
    print(video["title"])
